ter movement to parent paths
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Vim alias
alias v='vim'

# Colors
alias ls='ls --color=auto'
alias lla='ls -la'
alias grep='grep --color=auto'
alias tree='tree -C'

# ToDo
alias todo='$EDITOR $HOME/.todo'

# Connection speed test
alias speedtest='curl http://cachefly.cachefly.net/100mb.test > /dev/null'

